name = "austin-tx-parks"
account_id = "28b639294a6959cfb08ba53249e9ae7f"
type = "webpack"
workers_dev = true

[site]
bucket = "./build"
entry-point = "./workers-site"

[env.production]
zone_id = "dffa34a346973495431eb3b5a5f9fb89"
route = "austin-texas-parks.worldpeace.io/*"